name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment directory
        id: envdir
        run: |
          echo "dir=terraform/environments/dev" >> $GITHUB_OUTPUT  # Directorio 'dev' de Terraform
          echo "apply=false" >> $GITHUB_OUTPUT  # Inicialmente 'false' para el apply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ steps.envdir.outputs.dir }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ${{ steps.envdir.outputs.dir }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ steps.envdir.outputs.dir }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ steps.envdir.outputs.dir }}

  manual-apply:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && steps.envdir.outputs.apply == 'false' && github.ref == 'refs/heads/main'

    steps:
      - name: Wait for manual approval
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: apply-terraform.yml  # Trigger another workflow for apply
