name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite ejecución manual

env:
  TF_WORKSPACE: "dev"
  TF_DIR: "terraform/environments/dev"

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

  plan:
    name: Terraform Plan
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Generate Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_DIR }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ github.sha }}
          path: ${{ env.TF_DIR }}/tfplan

  notify:
    name: Notify Jenkins
    needs: plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Jenkins
        uses: machine-learning-apps/trigger-jenkins@master
        with:
          url: "http://your-jenkins-url/generic-webhook-trigger/invoke"
          token: "${{ secrets.JENKINS_TRIGGER_TOKEN }}"
          parameters: '{"sha":"${{ github.sha }}", "ref":"${{ github.ref }}"}'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'