---
- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: restart apache

- name: Configure WordPress virtual host
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: restart apache

- name: Enable WordPress site
  shell: /usr/sbin/a2ensite wordpress.conf
  notify: restart apache

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: restart apache