---
- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: restart apache

- name: Configure WordPress virtual host
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: restart apache

- name: Enable WordPress site
  file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  notify: restart apache

- name: Disable default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache