---
- name: Install System Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ system_packages }}"

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod {{ item }}
  loop: [ 'rewrite', 'ssl']

- name: Crear un certificado SSL autofirmado
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/{{ apache_vhost_name }}.key
    -out /etc/ssl/certs/{{ apache_vhost_name }}.crt
    -subj "/C={{ C }}/ST={{ ST }}/L={{ L }}/O={{ O }}/OU={{ OU }}/CN={{ CN }}"
  become: yes
  notify: restart apache