# Apache Configuration
apache_listen_ports:
  - 80
  - 443
apache_vhost_name: "2asir.es"
apache_ssl_cert: "/etc/ssl/certs/{{ apache_vhost_name }}.crt"
apache_ssl_key:  "/etc/ssl/private/{{ apache_vhost_name }}.key"

# System Configuration
system_packages:
  - apache2
  - mysql-server
  - python3-pymysql
  - php
  - php-mysql
  - libapache2-mod-php
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip

# MySQL Configuration
mysql_root_password: "secure_root_password"
mysql_db_name:       "wordpress"
mysql_db_user:       "wpuser"
mysql_db_password:   "secure_db_password"

# SSL Certificate Signing Info (opcional para generar CSR)
ssl_country:      "ES"
ssl_state:        "Córdoba"
ssl_locality:     "Córdoba"
ssl_organization: "dev"
ssl_ou:           "dev"
ssl_common_name:  "{{ apache_vhost_name }}"

# SSH / Bastion
ansible_user:                        ubuntu
ansible_ssh_private_key_file:       ../modules/ec2/.ssh/{{ params.ENVIRONMENT }}-wp-key.pem
bastion_user:                        ubuntu
bastion_host:                        "{{ bastion_public_ip.value }}"
ansible_ssh_common_args:            "-o ProxyJump={{ bastion_user }}@{{ bastion_host }}"

# Infraestructura
db_host:                             "{{ rds_endpoint.value }}"
elb_dns:                             "{{ elb_dns_name.value }}"