---
# Apache Configuration
apache_listen_ports:
  - 80
  - 443
apache_vhost_name: "devDomain.com"
apache_ssl_cert: "/etc/ssl/certs/devDomain.crt"
apache_ssl_key: "/etc/ssl/private/devDomain.key"

# MySQL Configuration
mysql_root_password: "secure_root_password"
mysql_db_name: "wordpress"
mysql_db_user: "wpuser"
mysql_db_password: "secure_db_password"

# WordPress Configuration
wp_admin_user: "admin"
wp_admin_password: "Root1234$"
wp_admin_email: "admin@devDomain.com"
wp_site_title: "My WordPress Site"
wp_site_url: "https://devDomain.com"